spring:
    application:
        name: "configserver"
    profiles:
#        active: native
        active : git
    cloud:
        config:
            server:
#                native:
##                    searchLocations: "classpath:/config/"
#                    searchLocations: "file:///C://Users//SHIVA//Desktop//Sample-Data//config"
                git:
                    uri: "https://github.com/shiva-kumar-45/eazybytes-config.git"
                    default-label: main
                    timeout: 5
                    clone-on-start: true
                    force-pull: true
server:
    port: 8071

encrypt:
    key: "45D81EC1EF61DF9AD8D3E5BB397F9"
