spring:
  config:
    activate:
      on-profile: "qa"
build:
  version : "12.00"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "sri sai - QA Lead"
    email: "srisai@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934