spring:
  config:
    activate:
      on-profile: "prod"
build:
  version : "10.69"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "sharan  sharma- producr owner"
    email: "sharan@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934